version: '3.3'
services:
  bbb-streamer:
    image: ghcr.io/sukso96100/bbb-nginx-rtmp:bigbluebutton-livestreaming
    container_name: liveStreaming
    shm_size: '2gb'
    env_file: .env
    volumes:
      - ./videodata:/video
  nginxrtmp:
    image: tiangolo/nginx-rtmp
    container_name: nginxrtmpName
    ports:
      - 1935:1935
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  stunnel:
    image: ghcr.io/sukso96100/bbb-nginx-rtmp:stunnel
    container_name: stunnelName
    volumes:
      - ./stunnel/conf.d/:/etc/stunnel/conf.d/
